apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nnrq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nnrq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nnrq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nnrq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nnrq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjmh-tenant/rhtap-demo-app/hacbs-test-project-nnrq@sha256:9a3896b9da290fc92353a6d69b41e06a6bfddfa9b77cbb4cc352b3edcd398123
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
